credentials = {
    'SPOTIFY_ID': "ADD YOUR SPOTIFY ID HERE",
    'SPOTIFY_SECRET': "ADD YOUR SPOTIFY SECRET HERE",
    'AWS_KEY_ID': "ADD YOUR AWS ID HERE",
    'AWS_KEY_SECRET': "ADD YOUR AWS SECRET HERE",
    'AWS_BUCKET_NAME' : "ADD YOUR AWS BUCKET NAME HERE"
}
